# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39b36e68edea9abe2a0907f370f6807e134cec6740585fe63b7735c47bfe0e46445b86b0fcb8785896288624829e2aa49687f40b08e3bf1676ef9405446d248

test:
  secret_key_base: c4e3117730da9a381dd90c492f8b7da7c59c7f71e391e6211933a87bee4d4c837ca73a54d5fc07b914bf549b0b7d61831b1424996ed698ce5c984f5f58ca69be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
